### ISSUE TITLE
About dynamic scene generation

### ISSUE THREAD

**Issue by mch5048** [NanboLi/CLEVR-Object-Centric#1]
Hi, thanks for sharing your insightful method Dymon. I really liked the neat idea.

I am also interested in the object-centric learning in the multi-view, dynamic scenes.
That being said, I want to start from your multi-view dynamic CLEVR3D data used in Dymon paper.

It seems like the dynamic scene generation code is not fully released in this repo, so I am wondering if I can
get the updated version of the data generation code.

Thanks in advance!

**Comment by NanboLi** [comment]
> Hi, thanks for sharing your insightful method Dymon. I really liked the neat idea.
> 
> I am also interested in the object-centric learning in the multi-view, dynamic scenes. That being said, I want to start from your multi-view dynamic CLEVR3D data used in Dymon paper.
> 
> It seems like the dynamic scene generation code is not fully released in this repo, so I am wondering if I can get the updated version of the data generation code.
> 
> Thanks in advance!

Hi, thanks for your interest. The dynamic scene generator is uploaded.

**Comment by mch5048** [comment]
Thanks a lot for your consideration.
