### ISSUE TITLE
Randomizing the background appearance

### ISSUE THREAD

**Issue by mch5048** [NanboLi/CLEVR-Object-Centric#2]
Hi, thanks for sharing then dynamic scene generator. The generated data really helped verifying my research and I will definitely cite your paper.

To evaluate the scalability of my method, I'd like to randomize the background appearance which is red walls and some kind of marble floors. I'm a bit newbie to the blenderpy and having trouble with changing their appearance.

I wish I could know how to change the background appearance and wish your generous advice.

Thanks!

**Comment by NanboLi** [comment]
Hi, one can create different `.blend` - with varying appearances of background - and place them in the 
`/dynamic_scene_generator/data` folder, then load them on the fly in rendering. Check `line 423` in the `/dynamic_scene_generator/dm_data_generator.py` file for a possible place to add such randomness. Thanks

**Comment by mch5048** [comment]
Thank you for your help!
